######################################################################
# Automatically generated by qmake (1.07a) Tue May 9 21:01:59 2017
######################################################################

TEMPLATE = app
DEPENDPATH += import plugin
INCLUDEPATH += . plugin

# Input
HEADERS += duration.h \
           soapH.h \
           soapStub.h \
           stdsoap2.h \
           wsdd.h \
           import/c14n.h \
           import/dom.h \
           import/ds.h \
           import/ds2.h \
           import/ref.h \
           import/ser.h \
           import/soap12.h \
           import/stdstring.h \
           import/stl.h \
           import/stldeque.h \
           import/stllist.h \
           import/stlset.h \
           import/stlvector.h \
           import/WS-example.h \
           import/WS-Header.h \
           import/wsa.h \
           import/wsa3.h \
           import/wsa4.h \
           import/wsa5.h \
           import/wsc.h \
           import/wsc2.h \
           import/wsdd.h \
           import/wsdd10.h \
           import/wsdx.h \
           import/wsp.h \
           import/wsrm.h \
           import/wsrm4.h \
           import/wsrm5.h \
           import/wsrp.h \
           import/wsrx.h \
           import/wsrx5.h \
           import/wsse.h \
           import/wsse11.h \
           import/wsse2.h \
           import/wst.h \
           import/wstx.h \
           import/wsu.h \
           import/xenc.h \
           import/xlink.h \
           import/xmime.h \
           import/xmime4.h \
           import/xmime5.h \
           import/xml.h \
           import/xmlmime.h \
           import/xmlmime5.h \
           import/xop.h \
           import/xsd.h \
           plugin/cacerts.h \
           plugin/calcrest.h \
           plugin/httpda.h \
           plugin/httpdatest.h \
           plugin/httpform.h \
           plugin/httpget.h \
           plugin/httpgettest.h \
           plugin/httpmd5.h \
           plugin/httpmd5test.h \
           plugin/httppost.h \
           plugin/httpposttest.h \
           plugin/logging.h \
           plugin/md5evp.h \
           plugin/mecevp.h \
           plugin/plugin.h \
           plugin/smdevp.h \
           plugin/threads.h \
           plugin/wsaapi.h \
           plugin/wsddapi.h \
           plugin/wsrmapi.h \
           plugin/wsse2api.h \
           plugin/wsseapi.h
SOURCES += dom.c \
           duration.c \
           onvif_client.c \
           onvif_config.c \
           onvif_muticast.c \
           onvif_osd.c \
           onvif_ptz.c \
           soapC.c \
           soapClient.c \
           stdsoap2.c \
           import/WS-example.c \
           plugin/cacerts.c \
           plugin/httpda.c \
           plugin/httpdatest.c \
           plugin/httpform.c \
           plugin/httpget.c \
           plugin/httpgettest.c \
           plugin/httpmd5.c \
           plugin/httpmd5test.c \
           plugin/httppost.c \
           plugin/httpposttest.c \
           plugin/logging.c \
           plugin/md5evp.c \
           plugin/mecevp.c \
           plugin/plugin.c \
           plugin/smdevp.c \
           plugin/threads.c \
           plugin/wsaapi.c \
           plugin/wsddapi.c \
           plugin/wsrmapi.c \
           plugin/wsse2api.c \
           plugin/wsseapi.c \
           plugin/wsseapi.cpp
